-- 20260619000003_viewer_tokens.sql
-- Created: 2026-06-19 (task #45 — PG-backed viewer token store)
--
-- Background (doc/15 §3.2 + wiki/webui.md §6.6):
--   Viewer tokens were issued into two **independent** in-process
--   stores: webui `TokenSet.viewer_tokens` and JNI
--   `VIEWER_TOKEN_STORE`. A token issued via Java `/biocapital
--   admin grant_viewer` lived in the JNI store and was therefore
--   invisible to the webui auth middleware (401 unauthorized).
--
-- Strategy (per task #45 decision):
--   - Make this table the authoritative store. WebUI's
--     `verify_token` first consults the in-memory cache (fast
--     path) and falls through to PG (correctness path). Issuing
--     a token double-writes to in-memory + PG.
--   - Heap table (no partitioning). Token count is bounded
--     (a handful per active player; revoke sweeps purge stale
--     rows). Monthly partitioning from the audit_* tables is
--     audit-specific; reusing it would be over-engineering.
--   - `body` is `UNIQUE` so the verifier can do a single
--     index-driven lookup. BYTEA holds the 32-byte viewer body
--     (last 16 bytes = subject UUID big-endian — matches the
--     wire form on the webui side).
--   - `revoked_at IS NULL` means "active". `expires_at < NOW()`
--     means "expired"; both filters apply for `list_active`.
--
-- Idempotency: every CREATE uses IF NOT EXISTS so a partial
-- run can resume. The UNIQUE constraint on `body` is what the
-- verifier relies on; an UNIQUE INDEX would also work but a
-- constraint is a stronger SQL contract (covers re-checks).

BEGIN;

CREATE TABLE IF NOT EXISTS viewer_tokens (
    token_id        UUID         PRIMARY KEY,             -- generated by issuer (Uuid::new_v4)
    subject_uuid    UUID         NOT NULL,                -- player UUID the token is scoped to
    body            BYTEA        NOT NULL UNIQUE,         -- 32 raw bytes (hex body without "v1." prefix)
    issued_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ  NOT NULL,
    revoked_at      TIMESTAMPTZ,                          -- NULL = not revoked
    issued_by       TEXT         NOT NULL,                -- 'WEBUI_ADMIN' | 'JAVA_JNI' | 'PG_RELOAD'
    request_id      UUID                                  -- idempotency anchor
);

-- Per-subject reverse-chronological scans
-- (e.g. "list every token issued to player X" for audit).
CREATE INDEX IF NOT EXISTS idx_viewer_tokens_subject
    ON viewer_tokens (subject_uuid);

-- For periodic sweeper that flips expired-but-not-revoked rows
-- out of the active set (the verifier itself also filters by
-- `expires_at > NOW()` so the index is mostly cosmetic, but
-- `list_active` does run a range scan).
CREATE INDEX IF NOT EXISTS idx_viewer_tokens_expires
    ON viewer_tokens (expires_at);

COMMENT ON TABLE  viewer_tokens IS
    'Authoritative store for viewer-token issuance (task #45 — webui ↔ JNI sync). Each row is one issued token; the verifier (auth.rs) consults this table when the in-memory cache misses. Body is 32 raw bytes (last 16 = subject UUID big-endian — wire-compatible with the existing v1.<64hex> format).';
COMMENT ON COLUMN viewer_tokens.token_id IS
    'UUIDv4 minted by the issuer (webui admin handler or, follow-up, the JNI dispatch path).';
COMMENT ON COLUMN viewer_tokens.body IS
    '32-byte viewer token body. UNIQUE so the verifier can do an index-driven `find_by_body`. The hex-encoded form is the 64 chars after "v1." in the wire token.';
COMMENT ON COLUMN viewer_tokens.issued_by IS
    'WEBUI_ADMIN (POST /admin/grant_viewer handler) | JAVA_JNI (Java-side /biocapital admin grant_viewer — currently NOT writing here; JNI side deferred to a follow-up task) | PG_RELOAD (manual seed / restore).';
COMMENT ON COLUMN viewer_tokens.request_id IS
    'Idempotency anchor — duplicate inserts with the same request_id should be a no-op. The repository enforces this via ON CONFLICT (body) DO NOTHING semantics.';

COMMIT;